services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: mydatabase
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"']
            interval: 1s
            timeout: 5s
            retries: 10
        ports:
            - '5432:5432'
